trigger:
- main

pool:  ctg-ak-dev
  # name: ctg-ak-dev

steps:
- script: |
   ls -R
   
   echo "Start arm  template deployments"
  displayName: 'Command Line Script'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    azureResourceManagerConnection: 'ADF_CONN'
    subscriptionId: '347fc977-961b-4016-bf42-a96ab3b85478'
    resourceGroupName: 'ctg-a5665-resource-east'
    location: 'East US'
    csmFile: template.json
    csmParametersFile: parameters.json
    deploymentMode: Complete

- script: |
   ls -la 
   echo "Done with installation"
   ls -R
   cat template.json
   cat parameters.json
  displayName: 'Command Line Script'

- script: |
    mkdir filenew
    ls -R 
    uname -a 
  displayName:  'Run another scripts'  



